### ISSUE TITLE
Add conditional for OT features 

### ISSUE THREAD

**Issue by NeilSureshPatel** [simoncozens/shaperglot#11]
Currently when checking for orphaned marks with smcp activate it will return the results for the original list of glyphs if the font does not have an smcp feature defined. This is giving duplicate errors since we am also checking for orphaned marks for original forms.

**Comment by simoncozens** [comment]
OK, I've done this, and the way to use it is:

```yaml
- check: no_orphaned_marks
  input:
    text: aasaea᷆a᷇a᷆a᷇e᷆e᷇e᷆e᷇ɛ́ɛ̀ɛ̂ɛ̌ɛ̄ɛ᷆ɛ᷇ɛ᷆ɛ᷇...
    features:
      smcp: true
  conditions:
    features:
      - smcp
```
